Support icons in selected item also, not only in list of options
sa-si-dev/virtual-select pull request #337
Opened 2024-05-23 11:41 UTC by AlexeySemenko

added config option selectedLabelRenderer, same as labelRenderer to allow showing icons or other custom content in selected item when the select is closed

2024-06-04 21:43 UTC, gnbm commented
@AlexeySemenko can you please add more context to the PR, including running tests and maybe including tests runs (example, something more aligned with this [PR](https://github.com/sa-si-dev/virtual-select/pull/325))

2024-06-04 22:01 UTC, gnbm commented on dist/virtual-select.js
`dist/` files should not be committed

2024-06-04 22:01 UTC, gnbm commented on package-lock.json
`package-lock.json` file should not be committed

2024-06-05 09:23 UTC, abenhamdine commented on docs/examples.md
> +Use `labelRenderer` callback function to add image, icon, or custom content to itmes
```suggestion
Use `labelRenderer` callback function to add image, icon, or custom content to items
```

2024-06-05 10:05 UTC, gnbm requested changes

2024-06-05 10:05 UTC, gnbm commented on dist-archive/virtual-select-1.0.44.min.js
@AlexeySemenko Please don't commit the `dist` file since this is only done when a new release is created

2024-06-05 10:05 UTC, gnbm commented on dist/virtual-select.js
@AlexeySemenko Please don't commit the `dist` file since this is only done when a new release is created

2024-06-05 10:05 UTC, gnbm commented on dist/virtual-select.min.js
@AlexeySemenko Please don't commit the `dist` file since this is only done when a new release is created

2024-06-05 17:49 UTC, gnbm approved these changes
LGTM 👍🏻

2024-06-10 22:50 UTC, gnbm commented
@AlexeySemenko once you resolve the conflicts the PR should be good to go and get merged 👍🏻

2024-06-13 07:08 UTC, AlexeySemenko commented
> @AlexeySemenko once you resolve the conflicts the PR should be good to go and get merged 👍🏻

conflict resolved

2024-06-13 10:43 UTC, merged