Added functionality to mark matched search term
sa-si-dev/virtual-select pull request #6
Opened 2021-02-04 14:36 UTC by frg

Added functionality to mark matched search term with the HTML tag `mark`. The option is off by default to avoid breaking changes.

2021-02-04 15:45 UTC, sa-si-dev commented on src/virtual-select.js
> +        /** remove previous modifications to the label */
Define a variable `markSearchResults` outside of the loop and use here instead of accessing directly from `this` object.

2021-02-04 15:48 UTC, sa-si-dev commented on src/virtual-select.js
> +        if (this.markSearchResults) {
This block could be changed as below. This way we can have multiple `mark` tag in a lable.

```js
if (markSearchResults) {
  d.label = d.label.replace(new RegExp(`(${searchValue})`, 'gi'), `<mark>$1</mark>`);
}
```

2021-02-04 15:50 UTC, sa-si-dev commented on docs/assets/script.js
> +    options: getOptions(0),
We could call `getOptions()` method without any argument, to use default count.

2021-02-04 15:52 UTC, sa-si-dev requested changes
Thanks for your contribution.

Please check my review comments.

2021-02-04 15:57 UTC, sa-si-dev commented
If you have interest, you can work on below feature.

https://github.com/sa-si-dev/virtual-select/issues/5

2021-02-04 15:57 UTC, frg commented
I've updated the pr with the changes you suggested. Thanks for taking the time to review this!

2021-02-04 15:59 UTC, frg commented
> If you have interest, you can work on below feature.
> 
> #5

I think I'll work on #4 first as that's a feature that I'm also looking for if that's okay.

2021-02-04 16:02 UTC, sa-si-dev commented
I have already implemented https://github.com/sa-si-dev/virtual-select/issues/4 

I will check in it soon.

2021-02-04 16:03 UTC, frg commented
> I have already implemented #4
> 
> I will check in it soon.

Perfect! I'll work on the other issue when I get some time.

2021-02-04 16:03 UTC, sa-si-dev commented
> > I have already implemented #4
> > I will check in it soon.
> 
> Perfect! I'll work on the other issue when I get some time.

Thanks

2021-02-04 16:04 UTC, sa-si-dev commented
> I've updated the pr with the changes you suggested. Thanks for taking the time to review this!

I will check and approve

2021-02-04 16:18 UTC, merged

2021-02-05 08:47 UTC, frg commented
@sa-si-dev I've found a small bug with this pr. I'll create another pr with the fix once my open pr is closed as I've branched off from that pr's branch by mistake.

2021-02-05 15:51 UTC, sa-si-dev commented
@frg I have moved the logic to set `<mark>` element, from `setSearchValue()' to 'renderOptions()'  method, to improve performance.